#	$Id$
define(`confMAPDEF', `-DNDBM')
define(`confENVDEF', `-DUNICOS')
define(`confOPTIMIZE', `-O')
define(`confINSTALL', `cpset')
define(`confMBINDIR', `/usr/lib')
define(`confSBINDIR', `/usr/etc')
define(`confUBINDIR', `/usr/bin')
define(`confEBINDIR', `/usr/lib')
