#	from: @(#)Makefile	5.25.1.1 (Berkeley) 5/7/91
#	$Id$

SUBDIR=	csu libarch libc libcompat libcrypt libcurses libedit libkvm libl \
	libm libpcap libresolv librpcsvc libskey libtelnet libterm libutil liby

.include <bsd.subdir.mk>
