#
# $Id$
#
NOMAN=		#defined

.include <bsd.own.mk>

PROG=		npppdctl
SRCS=		npppdctl.c debugutil.c

CPPFLAGS+=	-I${.CURDIR}/../npppd -I${.CURDIR}/../common

.include <bsd.prog.mk>
.PATH:		${.CURDIR}/../common
