#	$Id$

KMINCLUDES=	arch/m88k/DEFS.h arch/m88k/SYS.h
#KMSRCS=	bcmp.S bzero.S ffs.S strcat.c strcmp.S strcpy.S strlen.S strncmp.S \
#	strncpy.S htonl.S htons.S ntohl.S ntohs.S
KMSRCS=	htonl.S htons.S ntohl.S ntohs.S
