#!/bin/sh
# $Id$
if test "X$FAST" != "X" ; then echo "Not running $0" ;  exit 0 ; fi
FS=${FS:-${objdir}/../appl/fs/fs}
TARBOLL=$AFSROOT/stacken.kth.se/ftp/pub/gnu/emacs/emacs-20.5a.tar.gz
file $TARBOLL >&4 || exit 1
${FS} conn disconn
gzip -dc $TARBOLL | tar xvf - >&4 || exit 1
${FS} conn conn
