#	$Id$

NOMAN=

BINDIR=	/usr/libexec

CFLAGS+=-I${.CURDIR} -I${.CURDIR}/../common \
	-I${.CURDIR}/../arch -I${.CURDIR}/../arch/${MACHINE_ARCH}
YFLAGS=

LIBCC1!= cd $(.CURDIR)/../common; \
	printf "xxx:\n\techo \$${.OBJDIR}/libcc1.a\n" | ${MAKE} -r -s -f - xxx

LDADD+=${LIBCC1} -lgnumalloc
DPADD+= /usr/lib/libgnumalloc.a

.include <bsd.prog.mk>
