#	from: @(#)Makefile	5.7 (Berkeley) 4/1/91
#	$Id$

SUBDIR=	atrun comsat fingerd ftpd getNAME getty identd lfs_cleanerd \
	mail.local makekey makewhatis rexecd rlogind rshd rpc.lockd \
	rpc.rquotad rpc.rstatd rpc.rusersd rpc.rwalld rpc.sprayd \
	rpc.yppasswdd talkd telnetd tftpd uucpd

.include <bsd.subdir.mk>
